# No Podfile.local stuff in here, as it completely fubar's the pod setup.

source 'https://github.com/CocoaPods/Specs.git'

target 'Pajdeg', :exclusive => true do
  pod "PajdegPDF", :path => "../"
  pod "PajdegCore", "~> 0.0.6"
end

target 'Tests', :exclusive => true do
  pod "PajdegPDF", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
