# From: http://www.cocoanetics.com/2014/07/development-pods/
# Allows per-dev overrides
local_podfile = "Podfile.local"
eval(File.open(local_podfile).read) if File.exist? local_podfile

target 'Pajdeg', :exclusive => true do
  pod "PajdegPDF", :path => "../"
  pod "PajdegCore", "~> 0.0.5"
end

target 'Tests', :exclusive => true do
  pod "PajdegPDF", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
